version: '3'
services:
  web:
    build: ./front-web/new_update
    ports:
      - "20450:20450"
    depends_on:
      - "db1"
      - "db2"
      - "db3"
    network_mode: bridge

  db1:
    image: mongo:latest
    ports:
      - "27017:27017"
    network_mode: bridge

  db2:
    image: mongo:latest
    ports:
      - "27018:27017"
    network_mode: bridge

  db3:
    image: mongo:latest
    ports:
      - "27019:27017"
    network_mode: bridge